name: Reavix CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zig-version: ["0.11.0"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Zig
        run: |
          curl -L "https://ziglang.org/builds/zig-linux-x86_64-${{ matrix.zig-version }}.tar.xz" | tar -xJ -C /tmp
          echo "$PWD/zig-linux-x86_64-${{ matrix.zig-version }}" >> $GITHUB_PATH

      - name: Build Core
        run: |
          scripts/setup.sh
          make -C src/core test

      - name: Lint C Code
        run: |
          clang-tidy --version
          find src/core -name '*.c' -exec clang-tidy {} \;

      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Security Audit
        uses: github/codeql-action/analyze@v2
